package ac.dia.weightwatcher.pojo;
// Generated Dec 27, 2017 2:42:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Activity generated by hbm2java
 */
public class Activity  implements java.io.Serializable {


     private Integer activityId;
     private String activityName;
     private Set dailylogs = new HashSet(0);

    public Activity() {
    }

	
    public Activity(String activityName) {
        this.activityName = activityName;
    }
    public Activity(String activityName, Set dailylogs) {
       this.activityName = activityName;
       this.dailylogs = dailylogs;
    }
   
    public Integer getActivityId() {
        return this.activityId;
    }
    
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }
    public String getActivityName() {
        return this.activityName;
    }
    
    public void setActivityName(String activityName) {
        this.activityName = activityName;
    }
    public Set getDailylogs() {
        return this.dailylogs;
    }
    
    public void setDailylogs(Set dailylogs) {
        this.dailylogs = dailylogs;
    }




}


