package ac.dia.weightwatcher.pojo;
// Generated Dec 27, 2017 2:42:36 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {
     private Integer courseId;
     private Users users=new Users();
     private Date startDate;
     private Date endDate;
     private double bmi;
     private Set dailylogs = new HashSet(0);

    public Course() {
    }

    public Course(Users users){
    this.users=users;
    }
    public Course(Users users, Date startDate, Date endDate, double bmi) {
        this.users = users;
        this.startDate = startDate;
        this.endDate = endDate;
        this.bmi = bmi;
    }
    public Course(Users users, Date startDate, Date endDate, double bmi, Set dailylogs) {
       this.users = users;
       this.startDate = startDate;
       this.endDate = endDate;
       this.bmi = bmi;
       this.dailylogs = dailylogs;
    }
   
    public Integer getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public double getBmi() {
        return this.bmi;
    }
    
    public void setBmi(double bmi) {
        this.bmi = bmi;
    }
    public Set getDailylogs() {
        return this.dailylogs;
    }
    
    public void setDailylogs(Set dailylogs) {
        this.dailylogs = dailylogs;
    }
}


