package ac.dia.weightwatcher.pojo;
// Generated Dec 27, 2017 2:42:36 PM by Hibernate Tools 4.3.1



/**
 * Dailymeal generated by hbm2java
 */
public class Dailymeal  implements java.io.Serializable {


     private Integer dailyMealId;
     private Dailylog dailylog=new Dailylog();
     private Meal meal=new Meal();
     private Double mealIntake;

    public Dailymeal() {
    }
     public Dailymeal(Dailylog dailylog){
        this.dailylog=dailylog;
     }
     public Dailymeal(Meal meal){
     this.meal=meal;
     }
    public Dailymeal(Dailylog dailylog, Meal meal) {
        this.dailylog = dailylog;
        this.meal = meal;
    }
    public Dailymeal(Dailylog dailylog, Meal meal, Double mealIntake) {
       this.dailylog = dailylog;
       this.meal = meal;
       this.mealIntake = mealIntake;
    }
   
    public Integer getDailyMealId() {
        return this.dailyMealId;
    }
    
    public void setDailyMealId(Integer dailyMealId) {
        this.dailyMealId = dailyMealId;
    }
    public Dailylog getDailylog() {
        return this.dailylog;
    }
    
    public void setDailylog(Dailylog dailylog) {
        this.dailylog = dailylog;
    }
    public Meal getMeal() {
        return this.meal;
    }
    
    public void setMeal(Meal meal) {
        this.meal = meal;
    }
    public Double getMealIntake() {
        return this.mealIntake;
    }
    
    public void setMealIntake(Double mealIntake) {
        this.mealIntake = mealIntake;
    }




}


