package ac.dia.weightwatcher.pojo;
// Generated Dec 27, 2017 2:42:36 PM by Hibernate Tools 4.3.1



/**
 * Deilymeasurement generated by hbm2java
 */
public class Dailymeasurement  implements java.io.Serializable {


     private Integer dailyMeasurementId;
     private Dailylog dailylog;
     
     private double waistSize;
     private double weight;
     private String shift;

    public Dailymeasurement() {
    }

    public Dailymeasurement(Integer dailyMeasurementId, Dailylog dailylog, double waistSize, double weight, String shift) {
        this.dailyMeasurementId = dailyMeasurementId;
        this.dailylog = dailylog;
        this.waistSize = waistSize;
        this.weight = weight;
        this.shift = shift;
    }

    public Integer getDailyMeasurementId() {
        return dailyMeasurementId;
    }

    public void setDailyMeasurementId(Integer dailyMeasurementId) {
        this.dailyMeasurementId = dailyMeasurementId;
    }

    public Dailylog getDailylog() {
        return dailylog;
    }

    public void setDailylog(Dailylog dailylog) {
        this.dailylog = dailylog;
    }

    public double getWaistSize() {
        return waistSize;
    }

    public void setWaistSize(double waistSize) {
        this.waistSize = waistSize;
    }

    public double getWeight() {
        return weight;
    }

    public void setWeight(double weight) {
        this.weight = weight;
    }

    public String getShift() {
        return shift;
    }

    public void setShift(String shift) {
        this.shift = shift;
    }

    
   


}


