package ac.dia.weightwatcher.pojo;
// Generated Dec 27, 2017 2:42:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Excercise generated by hbm2java
 */
public class Excercise  implements java.io.Serializable {


     private Integer excerciseId;
     private String excerciseName;
     private String type;
     private Integer time;
     private Integer burnCalorie;
     private Set dailyexercises = new HashSet(0);

    public Excercise() {
    }

    public Excercise(String excerciseName, String type, Integer time, Integer burnCalorie, Set dailyexercises) {
       this.excerciseName = excerciseName;
       this.type = type;
       this.time = time;
       this.burnCalorie = burnCalorie;
       this.dailyexercises = dailyexercises;
    }
   
    public Integer getExcerciseId() {
        return this.excerciseId;
    }
    
    public void setExcerciseId(Integer excerciseId) {
        this.excerciseId = excerciseId;
    }
    public String getExcerciseName() {
        return this.excerciseName;
    }
    
    public void setExcerciseName(String excerciseName) {
        this.excerciseName = excerciseName;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Integer getTime() {
        return this.time;
    }
    
    public void setTime(Integer time) {
        this.time = time;
    }
    public Integer getBurnCalorie() {
        return this.burnCalorie;
    }
    
    public void setBurnCalorie(Integer burnCalorie) {
        this.burnCalorie = burnCalorie;
    }
    public Set getDailyexercises() {
        return this.dailyexercises;
    }
    
    public void setDailyexercises(Set dailyexercises) {
        this.dailyexercises = dailyexercises;
    }




}


