package ac.dia.weightwatcher.pojo;
// Generated Dec 27, 2017 2:42:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Meal generated by hbm2java
 */
public class Meal  implements java.io.Serializable {


     private Integer mealId;
     private String mealName;
     private Integer mealUnit;
     private Integer mealCalorie;
     private Set dailymeals = new HashSet(0);

    public Meal() {
    }

    public Meal(String mealName, Integer mealUnit, Integer mealCalorie, Set dailymeals) {
       this.mealName = mealName;
       this.mealUnit = mealUnit;
       this.mealCalorie = mealCalorie;
       this.dailymeals = dailymeals;
    }
   
    public Integer getMealId() {
        return this.mealId;
    }
    
    public void setMealId(Integer mealId) {
        this.mealId = mealId;
    }
    public String getMealName() {
        return this.mealName;
    }
    
    public void setMealName(String mealName) {
        this.mealName = mealName;
    }
    public Integer getMealUnit() {
        return this.mealUnit;
    }
    
    public void setMealUnit(Integer mealUnit) {
        this.mealUnit = mealUnit;
    }
    public Integer getMealCalorie() {
        return this.mealCalorie;
    }
    
    public void setMealCalorie(Integer mealCalorie) {
        this.mealCalorie = mealCalorie;
    }
    public Set getDailymeals() {
        return this.dailymeals;
    }
    
    public void setDailymeals(Set dailymeals) {
        this.dailymeals = dailymeals;
    }




}


