package ac.dia.weightwatcher.pojo;
// Generated Dec 27, 2017 2:42:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private Integer age;
     private String gender;
     private Double weight;
     private Double height;
     private double waistSize;
     private Double bmi;
     private Set courses = new HashSet(0);

    public Users() {
    }

	
    public Users(double waistSize) {
        this.waistSize = waistSize;
    }
    public Users(String userName, Integer age, String gender,
   Double weight, Double height, double waistSize, Double bmi, Set courses) {
       this.userName = userName;
       this.age = age;
       this.gender = gender;
       this.weight = weight;
       this.height = height;
       this.waistSize = waistSize;
       this.bmi = bmi;
       this.courses = courses;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Double getWeight() {
        return this.weight;
    }
    
    public void setWeight(Double weight) {
        this.weight = weight;
    }
    public Double getHeight() {
        return this.height;
    }
    public void setHeight(Double height) {
        this.height = height;
    }
    public double getWaistSize() {
        return this.waistSize;
    }
    
    public void setWaistSize(double waistSize) {
        this.waistSize = waistSize;
    }
    public Double getBmi() {
        return this.bmi;
    }
    
    public void setBmi(Double bmi) {
        this.bmi = bmi;
    }
    public Set getCourses() {
        return this.courses;
    }
    public void setCourses(Set courses) {
        this.courses = courses;
    }




}


